backend:
  name: git-gateway
  repo: ShvetsViktor/monovision
  branch: main
  auth:
    client_id: Ov23liXsMUOgfHsgYnKL
  auth_scope: repo
local_backend: false

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }